FEDORA: immodule: fix a GCC warning
Signed-off-by: Cosimo Cecchi <cosimoc@gnome.org>

[Mingcong Bai: This is now an error:

gtk/gtkimmodule.c:665:49: error: passing argument 3 of 'g_hash_table_lookup_extended'
 from incompatible pointer type [-Wincompatible-pointer-types]
  665 |                                                 &context_id, NULL);
      |                                                 ^~~~~~~~~~~
      |                                                 |
      |                                                 gchar ** {aka char **}

Possibly due to recent GLib API changes.]

Link: https://src.fedoraproject.org/rpms/gtk2/blob/a3a398f4f95684dba7a461acf389626eb2a3b90e/f/gtk2-c89-2.patch
Signed-off-by: Mingcong Bai <jeffbai@aosc.io>